package Main;


import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.util.*;
import javax.mail.*;
import javax.mail.internet.*;
import javax.mail.internet.MimeMessage;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.plaf.PanelUI;
import static jdk.nashorn.internal.objects.NativeJava.to;
import static org.eclipse.persistence.logging.SessionLog.PROPERTIES;
import sun.awt.WindowClosingListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shreyas
 */
public class MainFrame extends javax.swing.JFrame {
 

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        
       
        initComponents();
        display(); 
        //menu();
    }
private void display(){
    
  
    try{
        Connection con = DB.getConnection();
            PreparedStatement ps1 = con.prepareStatement("select * from foodmenu" );
            ResultSet rs1 = ps1.executeQuery();
            Table.setModel(DbUtils.resultSetToTableModel(rs1));
            
            con.close();
        }catch(SQLException e){
            e.printStackTrace();
        }
    
}

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        mainFrame = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        id_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Quantity_txt = new javax.swing.JTextField();
        GenBill_Btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        receipt_txt = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        Phonetxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        Add_cust = new javax.swing.JButton();
        Admin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(java.awt.Color.white);

        mainFrame.setBackground(new java.awt.Color(204, 204, 204));
        mainFrame.setForeground(new java.awt.Color(204, 204, 204));
        mainFrame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Product_Name");
        mainFrame.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 90, 30));

        id_txt.setBackground(new java.awt.Color(204, 204, 204));
        id_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_txtActionPerformed(evt);
            }
        });
        mainFrame.add(id_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 60, 200, 24));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Quantity:");
        mainFrame.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 65, 26));

        Quantity_txt.setBackground(new java.awt.Color(204, 204, 204));
        Quantity_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Quantity_txtActionPerformed(evt);
            }
        });
        Quantity_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Quantity_txtKeyPressed(evt);
            }
        });
        mainFrame.add(Quantity_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 100, 200, 26));

        GenBill_Btn.setBackground(new java.awt.Color(204, 204, 204));
        GenBill_Btn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        GenBill_Btn.setForeground(new java.awt.Color(0, 0, 0));
        GenBill_Btn.setText("Genarate Bill");
        GenBill_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GenBill_BtnMouseClicked(evt);
            }
        });
        GenBill_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenBill_BtnActionPerformed(evt);
            }
        });
        mainFrame.add(GenBill_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 104, 30));

        receipt_txt.setBackground(new java.awt.Color(204, 204, 204));
        receipt_txt.setColumns(20);
        receipt_txt.setForeground(new java.awt.Color(0, 0, 0));
        receipt_txt.setRows(5);
        receipt_txt.setOpaque(false);
        jScrollPane1.setViewportView(receipt_txt);

        mainFrame.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 320, 250));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        mainFrame.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 0, 50, 433));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Mobile no.");
        mainFrame.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 65, 23));

        Phonetxt.setBackground(new java.awt.Color(204, 204, 204));
        Phonetxt.setForeground(new java.awt.Color(0, 0, 0));
        Phonetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhonetxtActionPerformed(evt);
            }
        });
        Phonetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PhonetxtKeyPressed(evt);
            }
        });
        mainFrame.add(Phonetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 20, 200, 25));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table);

        mainFrame.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 240));

        Add_cust.setBackground(new java.awt.Color(204, 204, 204));
        Add_cust.setForeground(new java.awt.Color(0, 0, 0));
        Add_cust.setText("ADD Customer");
        Add_cust.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_custMouseClicked(evt);
            }
        });
        mainFrame.add(Add_cust, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, 30));

        Admin.setBackground(new java.awt.Color(204, 204, 204));
        Admin.setForeground(new java.awt.Color(0, 0, 0));
        Admin.setText("Admin Login");
        Admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminMouseClicked(evt);
            }
        });
        Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminActionPerformed(evt);
            }
        });
        mainFrame.add(Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shreyas\\Documents\\NetBeansProjects\\BillingSystem\\src\\Main\\main.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        mainFrame.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GenBill_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenBill_BtnActionPerformed

    }//GEN-LAST:event_GenBill_BtnActionPerformed

    private void GenBill_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenBill_BtnMouseClicked
        // TODO add your handling code here:

        Connection conB = DB.getConnection();
        String Product_id;
        String name;
        String Price;
        String Quantity;
        String Total1;
        try{
            String phone=Phonetxt.getText();
            String email="";
            String custname="";
            PreparedStatement ps3 = conB.prepareStatement("select * from cust where PhoneNO=?" );
            ps3.setString(1,phone);
            ResultSet rs3 = ps3.executeQuery();
            while(rs3.next()){
                custname=rs3.getNString("Name");
                email=rs3.getString("Email");
            }
            PreparedStatement ps1 = conB.prepareStatement("select * from Bill" );
            ResultSet rs1 = ps1.executeQuery();
            receipt_txt.setText("-- RECEIPT --");
            receipt_txt.append("\n\nCustomer Name:-"+custname+"\nPhoneNO:-"+phone+"\nEmail-ID:-"+email);
            while(rs1.next()){

                Product_id=rs1.getString("Product_ID");
                name = rs1.getString("Name");
                Price = rs1.getString("Price");
                Quantity = rs1.getString("Quantity");
                Total1 = rs1.getString("Total");
                receipt_txt.append("\n\nPRODUCT ID: "+Product_id+ "\n\nPRODUCT Name: " +name+ "\n\nPRODUCT PRICE: " +Price+ "\n\nPRODUCT Quantity: " +Quantity+"\n\nTOTAL: "+ Total1);
            }
            PreparedStatement ps = conB.prepareStatement("select sum(Total) from Bill" );
            ResultSet rs = ps.executeQuery();
            while (rs.next()){
                String Total =rs.getString("sum(Total)");
             //   Total_txt.setText(Total);
                receipt_txt.append("\n\n TOTAL BILL:-"+Total );
            }
            receipt_txt.append("\n\n-- THANK YOU! --" );
            
            
            try{
                String host = "smtp.gmail.com";
                String user = "shreyasrtg";
                String pss = "shreyasrtg123";
                String to =email;
                String from = "Shreyas";
                String Subject = "Receipt";
                String message =receipt_txt.getText();
                boolean sessionDebug = false;
                Properties pros = System.getProperties();
                pros.put("mail.smtp.starttls.enable","true");
                pros.put("mail.smtp.host","host");
                pros.put("mail.smtp.port","587");
                pros.put("mail.smtp.starttls.required","true");
                java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
                Session mailSession = Session.getDefaultInstance(pros,null);
                mailSession.setDebug(sessionDebug);
                Message msg = new MimeMessage(mailSession);
                msg.setFrom( new InternetAddress(from));
                InternetAddress [] address = {new InternetAddress(to)};
                msg.setRecipients(Message.RecipientType.TO, address);
                msg.setSubject(Subject);
                msg.setSentDate(new Date());
                msg.setText(message);
                Transport transport = mailSession.getTransport("smtp");
                transport.connect(host,user,pss);
                transport.sendMessage(msg,msg.getAllRecipients());
                transport.close();
                JOptionPane.showMessageDialog(null,"message send sucessfully");
                 PreparedStatement ps2 = conB.prepareStatement("delete from Bill" );
            ps2.executeUpdate();
            conB.close();
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,ex);
            }

        }catch(SQLException e ){
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_GenBill_BtnMouseClicked

    private void Quantity_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Quantity_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Quantity_txtActionPerformed

    private void id_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_txtActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
    DefaultTableModel model = (DefaultTableModel)Table.getModel();
    int selectrowindex = Table.getSelectedRow();
    id_txt.setText(model.getValueAt(selectrowindex,1).toString());
    Quantity_txt.requestFocus();
        
        
    }//GEN-LAST:event_TableMouseClicked

    private void Quantity_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Quantity_txtKeyPressed
if(evt.getKeyCode()==10){
  if(Quantity_txt.getText().equals("")){
     JOptionPane.showMessageDialog(null,"Field Cannot be left Empty"); 
  }else{
    
           String name=id_txt.getText();
             int num=Integer.parseInt(Quantity_txt.getText());
              
        id_txt.setText("");
        Quantity_txt.setText("");
        	    Connection con = DB.getConnection();
                    Connection conB = DB.getConnection();
                    
                    	try {
			PreparedStatement ps = con.prepareStatement("select * from foodmenu where Name =?");
			ps.setString(1, name);
                        ResultSet rs = ps.executeQuery();
                        PreparedStatement ps1 = conB.prepareStatement("insert into Bill(Product_ID,Name,Price,Quantity,Total) values(?,?,?,?,?)");
                        int Total;
                        while (rs.next()){
                        ps1.setInt(1,rs.getInt("Product_ID") );
                        ps1.setString(2,rs.getString("Name") );
                        ps1.setInt(3,rs.getInt("Price") );
                        int price=rs.getInt("Price");
                        Total=price*num;
                        ps1.setInt(4,num );
                        ps1.setInt(5,Total);
                        }
                        ps1.executeUpdate();
                        conB.close();
                        con.close();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        }

}
    }//GEN-LAST:event_Quantity_txtKeyPressed

    private void PhonetxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PhonetxtKeyPressed
if(evt.getKeyCode()==10){
Quantity_txt.requestFocus();


      
} 
    }//GEN-LAST:event_PhonetxtKeyPressed

    private void PhonetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhonetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhonetxtActionPerformed

    private void AdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminMouseClicked
               
    }//GEN-LAST:event_AdminMouseClicked

    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
new Admin_login().setVisible(true);
this.dispose();
    }//GEN-LAST:event_AdminActionPerformed

    private void Add_custMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_custMouseClicked
new CustD().setVisible(true);    
this.dispose();
    }//GEN-LAST:event_Add_custMouseClicked
public void menu(){
    
        Connection con = DB.getConnection();
         String Product_id;
            String name;
            String Price;
        try{
            PreparedStatement ps1 = con.prepareStatement("select * from foodmenu" );
            ResultSet rs1 = ps1.executeQuery();
          //Menu_txt.setText("-- MENU --");
            while(rs1.next()){
           
            Product_id=rs1.getString("Product_ID");
            name = rs1.getString("Name");
            Price = rs1.getString("Price");
           // Menu_txt.append("\n\nPRODUCT ID: "+Product_id+ "\nPRODUCT Name: " +name+ "\nPRODUCT PRICE: " +Price );
             }
         con.close();
        }catch(SQLException e){
            e.printStackTrace();
        }
        
    
}

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
                
             }
        });
        
    }
   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_cust;
    private javax.swing.JButton Admin;
    private javax.swing.JButton GenBill_Btn;
    private javax.swing.JTextField Phonetxt;
    private javax.swing.JTextField Quantity_txt;
    private javax.swing.JTable Table;
    private javax.swing.JTextField id_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel mainFrame;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JTextArea receipt_txt;
    // End of variables declaration//GEN-END:variables
}
