/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Shreyas
 */
public class UpdateMenu extends javax.swing.JFrame {

    /**
     * Creates new form UpdateMenu
     */
    public UpdateMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Update_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        id_txt = new javax.swing.JTextField();
        price_txt = new javax.swing.JTextField();
        Add_btn = new javax.swing.JButton();
        Update_txt = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setForeground(new java.awt.Color(0, 0, 0));
        setSize(new java.awt.Dimension(450, 350));

        Update_panel.setBackground(new java.awt.Color(204, 204, 204));
        Update_panel.setForeground(new java.awt.Color(0, 0, 0));
        Update_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("PRODUCT ID:");
        Update_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 83, 26));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("PRODUCT PRICE:");
        Update_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 163, -1, 26));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("PRODUCT NAME:");
        Update_panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 118, -1, 26));

        name_txt.setBackground(new java.awt.Color(204, 204, 204));
        name_txt.setForeground(new java.awt.Color(0, 0, 0));
        name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_txtActionPerformed(evt);
            }
        });
        Update_panel.add(name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 240, 26));

        id_txt.setBackground(new java.awt.Color(204, 204, 204));
        id_txt.setForeground(new java.awt.Color(0, 0, 0));
        id_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_txtActionPerformed(evt);
            }
        });
        Update_panel.add(id_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 240, 26));

        price_txt.setBackground(new java.awt.Color(204, 204, 204));
        price_txt.setForeground(new java.awt.Color(0, 0, 0));
        price_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price_txtActionPerformed(evt);
            }
        });
        Update_panel.add(price_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 240, 26));

        Add_btn.setBackground(new java.awt.Color(204, 204, 204));
        Add_btn.setForeground(new java.awt.Color(0, 0, 0));
        Add_btn.setText("ADD PRODUCT");
        Add_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_btnMouseClicked(evt);
            }
        });
        Add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_btnActionPerformed(evt);
            }
        });
        Update_panel.add(Add_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        Update_txt.setBackground(new java.awt.Color(204, 204, 204));
        Update_txt.setForeground(new java.awt.Color(0, 0, 0));
        Update_txt.setText("UPDATE");
        Update_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_txtActionPerformed(evt);
            }
        });
        Update_panel.add(Update_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 107, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Logged in as: admin");
        Update_panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 31));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Update_panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 80, -1));

        Delete.setBackground(new java.awt.Color(204, 204, 204));
        Delete.setForeground(new java.awt.Color(0, 0, 0));
        Delete.setText("DELETE");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        Update_panel.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 84, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/450x350.jpg"))); // NOI18N
        Update_panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Update_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Update_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        new Delete().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new MainFrame().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void Update_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_txtActionPerformed
        // TODO add your handling code here:
        int count=-1;
        if(id_txt.getText().equals("")||name_txt.getText().equals("")||price_txt.equals("")){
            JOptionPane.showMessageDialog(null,"Field Cannot be left Empty");
        }else{

            Connection con = DB.getConnection();
            int id=Integer.parseInt(id_txt.getText());
            String name=name_txt.getText();
            int price=Integer.parseInt(price_txt.getText());

            try{
                PreparedStatement ps1 = con.prepareStatement("SELECT COUNT(*) FROM foodmenu WHERE Product_ID = ? " );
                ps1.setInt(1, id);
                ResultSet rs1 = ps1.executeQuery();
                while(rs1.next()){
                    count=rs1.getInt("COUNT(*)");
                }
                if(count==1){

                    PreparedStatement ps = con.prepareStatement("update foodmenu set Name = ?,Price = ? where Product_ID =? " );
                    ps.setString(1,name);
                    ps.setInt(2,price);
                    ps.setInt(3,id);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Updated Sucessfully");
                }else{
                    JOptionPane.showMessageDialog(null,"ID does not Exist");
                }
            }catch(SQLException e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_Update_txtActionPerformed

    private void Add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_btnActionPerformed
        if(id_txt.getText().equals("")||name_txt.getText().equals("")||price_txt.equals("")){
            JOptionPane.showMessageDialog(null,"Field Cannot be left Empty");
        }else{

            Connection con = DB.getConnection();
            int id=Integer.parseInt(id_txt.getText());
            String name=name_txt.getText();
            int price=Integer.parseInt(price_txt.getText());
            try{
                PreparedStatement ps = con.prepareStatement("insert into foodmenu(Product_ID,Name,Price) values(?,?,?)" );
                ps.setInt(1,id);
                ps.setString(2,name);
                ps.setInt(3,price);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Added Sucessfully");
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,"ID Already Exist");
                e.printStackTrace();
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_Add_btnActionPerformed

    private void Add_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_btnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Add_btnMouseClicked

    private void price_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price_txtActionPerformed

    private void id_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_txtActionPerformed

    private void name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_btn;
    private javax.swing.JButton Delete;
    private javax.swing.JPanel Update_panel;
    private javax.swing.JButton Update_txt;
    private javax.swing.JTextField id_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField name_txt;
    private javax.swing.JTextField price_txt;
    // End of variables declaration//GEN-END:variables
}
